name: Update Content from Bluesky

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-content:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: npm install
        
      - name: Update content from Bluesky
        env:
          BLUESKY_HANDLE: ${{ secrets.BLUESKY_HANDLE }}
          BLUESKY_APP_PASSWORD: ${{ secrets.BLUESKY_APP_PASSWORD }}
        run: npm run update-content
        
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT
        
      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "FHDSA Content Bot"
          git pull --rebase origin master
          git add _portfolio/2-announcements.md _portfolio/3-news.md
          git commit -m "🤖 Update content from Bluesky posts"
          git push origin master
        
      - name: No changes detected
        if: steps.git-check.outputs.changes != 'true'
        run: echo "No new content to update"
